name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '0 10 * * 0' # Run it every Sunday 10am UTC

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs:
          - 27.2
          - 28.2
          - 29.3
          - snapshot
        orgmode:
          - main
          - bugfix
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Org-Mode
        run: git clone --depth=1 --branch ${{matrix.orgmode}} git://git.savannah.gnu.org/emacs/org-mode.git ../org-mode

      - name: Generate Autoload
        run: |
          echo "autoloads:" > local.mk
          make
        working-directory: ../org-mode

      - run: make test
